baseURL = 'https://cdeever.github.io/home-relocate/'
languageCode = 'en-us'
title = 'Home Relocate'
theme = 'hugo-book'

enableGitInfo = true

# Book theme configuration
[params]
  BookTheme = 'auto'
  BookToC = true
  BookMenuBundle = '/menu'
  BookSection = 'docs'
  BookRepo = 'https://github.com/cdeever/home-relocate'
  BookSearch = true

[menu]
